apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "kibana-auth.fullname" . }}-sync-ldap
  labels:
    app: {{ template "kibana-auth.fullname" . }}-sync-ldap
    chart: {{ template "kibana-auth.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
spec:
  schedule: {{ .Values.syncLDAP.schedule| quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ template "kibana-auth.fullname" . }}-sync-ldap
          labels:
            app: {{ template "kibana-auth.fullname" . }}-sync-ldap
            release: {{ .Release.Name }}
        spec:
          restartPolicy: Never
          {{- if .Values.images.pullSecret }}
          imagePullSecrets:
    {{ toYaml .Values.images.pullSecret | indent 8 }}
          {{- end }}
          containers:
          - name: {{ template "kibana-auth.fullname" . }}-sync-ldap
            image: "{{ .Values.images.syncLDAP.repository }}:{{ .Values.images.syncLDAP.tag }}"
            imagePullPolicy: {{ .Values.images.pullPolicy }}
            env:
            - name: L2E_DEBUG
              value: {{ .Values.debug | quote }}
            - name: L2E_LDAP_DOMAIN
              value: {{ .Values.ldap.domain | quote }}
            - name: L2E_LDAP_PORT
              value: {{ .Values.ldap.port | quote }}
            - name: L2E_LDAP_SCHEMA
              value: {{ .Values.ldap.schema | quote }}
            - name: L2E_LDAP_BASE_DN
              value: {{ .Values.ldap.baseDN | quote }}
            - name: L2E_LDAP_FILTER
              value: {{ .Values.ldap.filter | quote }}
            - name: L2E_LDAP_GROUPS
              value: {{ include "dict2bash" .Values.ldap.groups }}
            - name: L2E_LDAP_GROUPS_LIST_KEY
              value: {{ .Values.ldap.groupListKey | quote }}
            - name: L2E_LDAP_KEY_FOR_USERNAME
              value: {{ .Values.ldap.keyForUsername | quote }}
            - name: L2E_LDAP_CA_FILE_PATH
              value: {{ .Values.ldap.CAFilePath | quote }}
            {{- if .Values.ldap.credsFromExistingSecret}}
            - name: L2E_LDAP_LOGIN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ldap.credsFromExistingSecret.secretName }}
                  key: {{ .Values.ldap.credsFromExistingSecret.loginField }}
            - name: L2E_LDAP_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ldap.credsFromExistingSecret.secretName }}
                  key: {{ .Values.ldap.credsFromExistingSecret.passField }}
            {{- end }}
            - name: L2E_ELASTIC_DOMAIN
              value: {{ .Values.elastic.domain | quote }}
            - name: L2E_ELASTIC_PORT
              value: {{ .Values.elastic.port | quote }}
            - name: L2E_ELASTIC_SCHEMA
              value: {{ .Values.elastic.schema | quote }}
            - name: L2E_ELASTIC_ROLES
              value: {{ include "dict2bash" .Values.elastic.roles }}
            - name: L2E_ELASTIC_ROLE_FOR_IMPORTED_USERS
              value: {{ .Values.elastic.roleForImportedUsers | quote }}
            - name: L2E_ELASTIC_INSECURE_TLS
              value: {{ .Values.elastic.insecureTLS | quote }}
            {{- if .Values.elastic.credsFromExistingSecret}}
            - name: L2E_ELASTIC_LOGIN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.elastic.credsFromExistingSecret.secretName }}
                  key: {{ .Values.elastic.credsFromExistingSecret.loginField }}
            - name: L2E_ELASTIC_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.elastic.credsFromExistingSecret.secretName }}
                  key: {{ .Values.elastic.credsFromExistingSecret.passField }}
            {{- end }}
            envFrom:
              - secretRef:
                  name: {{ template "kibana-auth.fullname" . }}-creds
          {{- with .Values.tolerations }}
          tolerations: {{ toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector: {{ toYaml . | nindent 12 }}
          {{- end }}
