apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kibana-auth.fullname" . }}-oauth2-proxy-config
  labels:
    app: {{ template "kibana-auth.fullname" . }}-oauth2-proxy
    chart: {{ template "kibana-auth.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  alpha-config.yaml: |
    {{- .Values.oauth2Proxy.alphaConfig | toYaml | nindent 4 }}
  config.cfg: |
    {{- range $key, $value := .Values.oauth2Proxy.config }}
    {{ $key }}={{ $value }}
    {{- end }}
