apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kibana-auth.fullname" . }}-creds
  labels:
    app: {{ template "kibana-auth.fullname" . }}
    chart: {{ template "kibana-auth.fullname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
type: Opaque
data:
  L2E_LDAP_LOGIN: {{ .Values.ldap.login  | b64enc | quote }}
  L2E_LDAP_PASS: {{ .Values.ldap.pass  | b64enc | quote }}
  L2E_ELASTIC_LOGIN: {{ .Values.elastic.login  | b64enc | quote }}
  L2E_ELASTIC_PASS: {{ .Values.elastic.pass  | b64enc | quote }}
